name: medium (Guava 30.1.1-jdk)
on:
  push:
    branches:
      - main
jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - name: Create build.gradle
        run: |
          cat <<EOF > build.gradle
            plugins { id 'java' }
            repositories { mavenCentral() }
            dependencies { implementation 'com.google.guava:guava:30.1.1-jre' }
          EOF
      - uses: kengotoda/setup-java@cache
        with:
          distribution: adopt
          java-version: 11
          cache: gradle
      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Download dependencies to local filesystem
        run: |
          gradle dependencies
  sequential:
    runs-on: ubuntu-latest
    needs: prepare
    strategy:
      matrix:
        num: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
    steps:
      - name: Create build.gradle
        id: initialize
        run: |
          cat <<EOF > build.gradle
            plugins { id 'java' }
            repositories { mavenCentral() }
            dependencies { implementation 'com.google.guava:guava:30.1.1-jre' }
          EOF
          echo "::set-output name=time_begin::$(($(date +%s%N)/1000000))"
      - uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 11
      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - id: complete
        run: |
          time_end=$(($(date +%s%N)/1000000))
          elapsed=$(( time_end - ${{ steps.initialize.outputs.time_begin }} ))
          echo "sequential,$elapsed" > sequential${{ matrix.num }}.txt
          gradle dependencies
      - uses: actions/upload-artifact@v2
        with:
          name: sequential${{ matrix.num }}
          path: sequential${{ matrix.num }}.txt
  parallel:
    runs-on: ubuntu-latest
    needs: prepare
    strategy:
      matrix:
        num: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
    steps:
      - name: Create build.gradle
        id: initialize
        run: |
          cat <<EOF > build.gradle
            plugins { id 'java' }
            repositories { mavenCentral() }
            dependencies { implementation 'com.google.guava:guava:30.1.1-jre' }
          EOF
          echo "::set-output name=time_begin::$(($(date +%s%N)/1000000))"
      - uses: kengotoda/setup-java@cache
        with:
          distribution: adopt
          java-version: 11
          cache: gradle
      - id: complete
        run: |
          time_end=$(($(date +%s%N)/1000000))
          elapsed=$(( time_end - ${{ steps.initialize.outputs.time_begin }} ))
          echo "parallel,$elapsed" > parallel${{ matrix.num }}.txt
          gradle dependencies
      - uses: actions/upload-artifact@v2
        with:
          name: parallel${{ matrix.num }}
          path: parallel${{ matrix.num }}.txt
  report:
    runs-on: ubuntu-latest
    needs:
      - sequential
      - parallel
    steps:
      - uses: actions/download-artifact@v2
        with:
          path: .
      - name: Prints a CSV report
        run: |
          echo "type,elapsed[ms]"
          cat */*.txt
